### PR TITLE
Adds PhantomJS test generators so that tests will fail on lint failures

### PR DESCRIPTION
**Pull request by pzuraq**
@sir-dunxalot This PR adds Phantom JS test generators which will cause failures when Sass errors exist. The code is mostly based on the same functionality in `broccoli-jscs` and the tests are ripped from there as well. Let me know if there's anything you'd like changed.

### CODE REVIEW

**Comment by sir-dunxalot** [comment]
This all look great! Is this ready for release now?

**Comment by pzuraq** [comment]
There was one strange bug, apparently we can't simply alias the `linter.format` function. Not sure why, don't have time to dig into it. But yeah, just tested and it's all working locally :+1:

**Comment by sir-dunxalot** [comment]
Perhaps aliasing is changing the context bound to the call? Either way, I will get this merged and released today.

**Comment by sir-dunxalot** [comment]
Released as `0.1.3`. This update should be applied to `ember-cli-sass-lint` (if you're using that) by reinstalling npm dependencies in your project.

**Pull request merged**
