### PR TITLE
Added support for the 'ignored' and 'included' config properties

### PR DESCRIPTION
**Pull request by chinthakagodawita**
This fixes sir-dunxalot/ember-cli-sass-lint#1.

This should probably be a temporary fix until a solution for sasstools/sass-lint#452 is found.

### CODE REVIEW

**Comment by sir-dunxalot** [comment]
Sorry for the slow response. This looks good! I really appreciate the time put into this. I will merge, update documentation, as soon as I can get to it.

**Comment by john-kurkowski** [comment]
Thanks for this. I needed it too. However the diff as is breaks test generation. See Sitback/broccoli-sass-lint#1. Merge/squash that PR into this one as you like.

**Comment by sir-dunxalot** [comment]
Good spot, John. I will investigate that when I merge this and will let you know if I have questions.

**Comment by chinthakagodawita** [comment]
@sir-dunxalot I've merged John's changes into the base PR to hopefully make things easier for you

**Comment by sir-dunxalot** [comment]
Ah, good work! Thank you.

**Comment by sir-dunxalot** [comment]
Released as `0.1.4`.

**Comment by chinthakagodawita** [comment]
Great, thanks!

**Pull request merged**
